apiVersion: v1
kind: Namespace
metadata:
  name: preview-env-sample
  labels:
    orbitdesktop.io/environment-id: env-sample
    orbitdesktop.io/owner: local
    orbitdesktop.io/template: web-postgres

