apiVersion: v1
kind: Secret
metadata:
  name: sample-app-db
  namespace: preview-env-sample
type: Opaque
stringData:
  database-url: postgres://orbit:temporary-password@postgres.preview-env-sample.svc.cluster.local:5432/orbit

